version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/var/www/prashantjain_me/
hooks:
  BeforeInstall:
     - location: scripts/clean_source.sh
       timeout: 300
       runas: root   
  AfterInstall:
    - location: scripts/copy_to_html.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/validate.sh
      timeout: 300
      runas: root
